# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7c1875dac1f92baac781a3bab5fe9f83e1170934be772177c231a21cf29e836f1f7f901aee962863d4d6c0acc76dcd72fd6b0982febbd6123f23ef2bebd854e

test:
  secret_key_base: e1e53307159f415f04f6c2531d234cc5339535bee0b71fc4cc96861117bafb9b4b3e34de055801becc60f69267f9b96b2e3cd072dd1d4f355adb15dbc4417fc2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
